### ISSUE TITLE
Error in popup.js causes alarm to fail

### ISSUE THREAD

**Issue by byteswitched** [snoringriceball/youtube-sleep-timer#2]
Error thrown on popup.js in line 7 character 74 after inputting any integer into the time field and hitting start:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'alarm') at popup.js:7:74`
It reads like something wasn't initialized correctly, but I sadly don't know enough about javascript to go in and fix the issues myself.

**Comment by snoringriceball** [comment]
Thanks for the comment! 
The latest push to master I believe should work well. However, the version published to the webstore was not in sync to what we had in master, this was due to a rushed attempt to solve a previously reported bug, we apologize for the inconvenience caused. 
Before chrome releases the new version, you can try loading the unpacked version by following the instructions in the readme. 
Again, sorry for the inconvenience :(

**Comment by snoringriceball** [comment]
Closing as version 2.2 of this extension on the webstore should resolve
